### PR TITLE
Make build.ps1 crossplatform

### PR DESCRIPTION
**Pull request by vors**
1. ~~Move `InstallAtom` into a separate step~~ Remove auto-install step from build script.
2. Move RunBuild and RunTests into functions so they can be reused
3. Leverage `Get-Command atom` as a cross-platform way of getting the atom executable path

### CODE REVIEW

**Comment by omniomi** [comment]
Looks good. Only one issue, the DownloadAtom function downloads the portable Atom so it doesn't create the Atom command, it needs to be called by path. It also downloads the Windows portable version. Not sure the best way to make that cross-platform.

**Comment by vors** [comment]
Oh I see. I think it's reasonable to ask the person to download atom manually for their platform in the error message instead. What do you think?

**Comment by omniomi** [comment]
I'd agree. The appveyor task relies on the portable version but I can be explicit instead of calling build.ps1 in appveyor.yml.

**Comment by omniomi** [comment]
I will merge this in tomorrow when I have time to fix Appveyor since it will break CI.

**Review by omniomi — APPROVED** [review]
LGTM

**Pull request merged**
